/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutgoingRouteImport } from './routes/outgoing'
import { Route as IncomingRouteImport } from './routes/incoming'
import { Route as IndexRouteImport } from './routes/index'

const OutgoingRoute = OutgoingRouteImport.update({
  id: '/outgoing',
  path: '/outgoing',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingRoute = IncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incoming': typeof IncomingRoute
  '/outgoing': typeof OutgoingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incoming': typeof IncomingRoute
  '/outgoing': typeof OutgoingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incoming': typeof IncomingRoute
  '/outgoing': typeof OutgoingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/incoming' | '/outgoing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/incoming' | '/outgoing'
  id: '__root__' | '/' | '/incoming' | '/outgoing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncomingRoute: typeof IncomingRoute
  OutgoingRoute: typeof OutgoingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outgoing': {
      id: '/outgoing'
      path: '/outgoing'
      fullPath: '/outgoing'
      preLoaderRoute: typeof OutgoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming': {
      id: '/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof IncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncomingRoute: IncomingRoute,
  OutgoingRoute: OutgoingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
